name: Deploy to AWS ECR and ECS

on:
  push:
    branches:
      - release

jobs:
<<<<<<< HEAD
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1  
=======
  deploy:
    runs-on: ubuntu-latest
>>>>>>> c721fb6574b5f2d25107a5c8fc5a511cb3328eef
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

<<<<<<< HEAD
    - name: Build Docker image
      run: |
        docker build --platform=linux/amd64 -t ${{ secrets.ECR_REPOSITORY }}:latest .
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
    
    - name: Output Image URI
      id: ecr
      run: echo "::set-output name=image_uri::${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest"

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - name: Run ECS Task
      run: |
        aws ecs run-task --cluster ${{ secrets.ECS }} --task-definition ${{ secrets.ECS_TASK_DEFINITION }}
=======
    - name: Build, tag, and push Docker image
      run: |
        docker build --platform=linux/amd64 -t ${{ secrets.ECR_REPOSITORY }}:latest .
        docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest
        docker push ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

    - name: Run ECS Task
      run: |
        aws ecs run-task --cluster ${{ secrets.ECS }} --task-definition ${{secrets.ECS_TASK_DEFINITION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
>>>>>>> c721fb6574b5f2d25107a5c8fc5a511cb3328eef
